---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: acmrepo-pvc
  namespace: acmrepo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: acmrepo
  volumeMode: Filesystem  
