---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-f5
  namespace: acmrepo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: acmrepo
  storageClassName: nfs-storage
  volumeMode: Filesystem  
