---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-f5
  namespace: apptest
  labels:
    appname: f5-hello-world
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
