---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-f5
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: dg8storageclass
  volumeMode: Filesystem
