---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-f5
  namespace: acmrepo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-storagecluster-ceph-rbdmirror
