---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-f5
  labels:
    appname: f5-hello-world
  namespace: acmrepo  
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ovirt-csi-sc
  resources:
    requests:
      storage: 2Gi
