---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-f52
  labels:
    appname: f5-hello-world
  namespace: acmrepo  
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbdmirror
  resources:
    requests:
      storage: 2Gi
