---
kind: Service
apiVersion: v1
metadata:
  name: f5-hello-world
  labels:
    app: f5-hello-world
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  selector:
    app: f5-hello-world
  type: ClusterIP
